= Changelog

This document provides information about changes that have been made for each new version
of the Signature Service Transaction Signing Library.

== Version 2505.1

=== Upgrade notes
Changes in preparation for moving to java 21 in Q4 2025.

=== Changes
* Replaced old test library org.codehaus.groovy.modules.http-builder:http-builder with com.squareup.okhttp3:okhttp
* Bump SLF4J to 2.0.17
* Upgraded JSON In Java to 20250517.
* Updated Spock Framework Core Module to 2.4-M6-groovy-3.0
* Removed not related internal build logic from build.gradle.
* Updated the Gradle Wrapper files(gradlew, gradlew.bat, gradle-wrapper.jar) to align with the configured Gradle version.
* Upgrades in SignTool CLI: Now allows explicitly setting the signature algorithm to be used.
* Fixed vulnerability CVE-2025-27820, derived from dependencies of eu.europa.ec.joinup.sd-dss:dss-service, by upgrading libraries:

    org.apache.httpcomponents.client5:httpclient5 to 5.4.4
    org.apache.httpcomponents.core5:httpcore5 to 5.3.4
    org.apache.httpcomponents.core5:httpcore5-h2 to 5.3.4

== Version 2503.1

=== Upgrade notes
This release contains *breaking changes*.

=== Improvements and bug fixes
* Upgraded eu.europa.ec.joinup.sd-dss to version 6.2
* Bundled validation policy now accepts the RSASSA-PSS algorithm for signatures, and on signing certificate
* Fixed thread-related issue causing "No pending transaction found with requestId: XXX" errors under high TPS.
* Changed the default signature algorithm from `SHA256withRSA` to `SHA512withRSAandMGF1`.
This can be overridden using:

    TransactionSigner signer = new TransactionSigner.Builder()
        .signatureAlgorithm("SHA256withRSA")

* Added DSS PAdES PDFBox dependency to resolve missing IPdfObjFactory implementation.
* Minor improvements to automatic stream closing, making it more concise.

== Version 2502.3

=== Improvements and bug fixes
* No change.

== Version 2502.1

=== Improvements and bug fixes
* Resolved build failure for tests caused by a missing spock-bom dependency.
* Upgraded com.github.johnrengelman.shadow from 6.1.0 to 7.1.2.
* Reformatted build.gradle to adopt the modern plugin application syntax.
* Removed redundant java plugin. Already applied by Java Library Plugin.

=== Upgrade notes
This release contains no breaking changes.

== Version 2501.1

=== Improvements and bug fixes
* Bump Gradle to 7.6.4 in wrapper.
* Bump Grails from 6.2.0 to 6.2.3.
* Bump Grails Gradle Plugin from 6.2.0 to 6.2.4.
* Bump Groovy to 3.0.23.
* Bump JSON In Java from 20240303 to 20250107.

=== Upgrade notes
This release contains no breaking changes.

== Version 2408.3

=== Upgrade notes
This release contains breaking changes.

=== Improvements and bug fixes
* Fixed thread-related issue causing "No pending transaction found with requestId: XXX" errors under high TPS.

== Version 2408.1

=== Improvements and bug fixes
* Bump SLF4J API Module to 2.0.16.
* Bump SLF4J Simple Provider to 2.0.16.
* Upgraded Gradle build tool to version 7.6.4.

=== Upgrade notes
This release contains no breaking changes.

== Version 2405.1

=== Improvements and bug fixes
* Bump SLF4J API Module to 2.0.13.
* Bump SLF4J Simple Provider to 2.0.13.
* Bump JSON In Java to 20240303.
* Added missing gradlew and gradlew.bat files.
* Fixed bug that caused memory issues after heavy usage.
* DSS library dependency has been upgraded to 5.13.
* Updated some deprecated methods.

=== Upgrade notes
Smaller improvements to logging. Now logging statements are using parameterized messages for improved performance.
Improvements to resource management by converting existing code to use try-with-resources for automatic closure.